command_timeout = 1500

[username]
show_always = true

[shell]
disabled = false

[git_branch]
always_show_remote = true

[git_status]
format= '([\[]($style) $all_status$ahead_behind[\]]($style) )'
style = 'bold white'
diverged = 'ğŸ˜µ[â‡¡${ahead_count}](bold green)[â‡£${behind_count}](bold red) '
conflicted = 'ğŸš© '
ahead = '[â‡¡${count}](bold green) '
behind = '[â‡£${count}](bold red) '
up_to_date = 'âœ“ '
untracked = 'ğŸ¤·[${count}](bold yellow) '
stashed = 'ğŸ“¦[${count}](bold grey) '
modified = 'ğŸ“[${count}](bold orange) '
staged = '[++${count}](green) '
renamed = 'ğŸ‘…[${count}](grey) '
deleted = 'ğŸ—‘[${count}](red) '
